### ISSUE TITLE
Memory leak in netty 4.1.7 when use SSL

### ISSUE THREAD

**Issue by liujinf** [wso2/carbon-transports#292]
Hello, 
We find this error When we test transports:
  Failed to mark a promise as failure because it has succeeded OutOfDirectMemoryError....
And find this issue:
  https://github.com/netty/netty/issues/6221

liuhf

**Comment by shafreenAnfar** [comment]
Hi Liuhaif,

We have upgraded the Netty version and also we fixed similar issue that was caused by not releasing NettyDataHolders. Please kindly let us know if you still face the same issue.

Thanks,
Shaf

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
