### ISSUE TITLE
[HTTP] No Content length Header in HTTP OPTIONS response

### ISSUE THREAD

**Issue by chamil321** [wso2/carbon-transports#348]
In HTTP OPTIONS Response, "Allow" and  "Content-length" headers are essential. Eventhough the Content-Length header is set in the response, Client shows the response avoiding it as follows,
```
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
content-encoding: gzip
transfer-encoding: chunked
```
This issue should be fixed in order to have "Content-length : 0" instead of transfer-encoding header.

**Comment by shafreenAnfar** [comment]
This have been fixed in the latest version. Hence, closing the issue.
