### ISSUE TITLE
Can't stream Files from MSF4J via new transport

### ISSUE THREAD

**Issue by thusithathilina** [wso2/carbon-transports#368]
With older transport[1], once the content is added to message, that was get written using the Writer. But with new transport/messaging this functionality doesn;t work as intended.

[1] - https://github.com/wso2/carbon-messaging/blob/master/components/src/main/java/org/wso2/carbon/messaging/CarbonMessage.java#L145

**Comment by shafreenAnfar** [comment]
This has been fixed in the latest version. Please do let us know if still face the same issue.
